# Changes here will be overwritten by Copier
_commit: 2024.04.03
_src_path: gh:zenml-io/template-starter
email: ''
full_name: ZenML GmbH
open_source_license: apache
project_name: ZenML Starter
version: 0.1.0
